version: "2"
services:
  wordpress:
    build:
      context: ./
      dockerfile: ./Dockerfile
    links:
      - db:mysql
      - mailhog
    ports:
      - 80:80
    domainname: env.localhost
    hostname: env
    volumes:
      - ./public:/var/www/html
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./db:/var/www/html/db
      - ./wp.sh:/var/www/html/wp.sh
      - ./phpconf.ini:/usr/local/etc/php/conf.d/phpconf.ini
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: docker
    depends_on:
      - mailhog
      - db

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

  wpcli:
    image: wordpress:cli
    volumes_from:
      - wordpress
    links:
      - db:mysql
    command: "sh wp.sh"
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: docker
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: docker
